"""
Shopfloor Copilot — Streamlit chat interface.

Runs with: streamlit run app/streamlit_app.py
Requires:  mock_mes_api.py running on localhost:8000
           FAISS index built (python -m app.rag)
           ANTHROPIC_API_KEY set in .env
"""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from dotenv import load_dotenv
load_dotenv()

import streamlit as st

from app.agent import run_agent

# ---------------------------------------------------------------------------
# Page config — must be first Streamlit call
# ---------------------------------------------------------------------------

st.set_page_config(
    page_title="Shopfloor Copilot",
    page_icon="🏭",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ---------------------------------------------------------------------------
# Sidebar
# ---------------------------------------------------------------------------

with st.sidebar:
    st.markdown("## 🏭 Shopfloor Copilot")
    st.markdown(
        "An AI assistant for automotive manufacturing operators and team leaders. "
        "Ask questions about standard procedures, live line performance, or raise "
        "a formal incident ticket — all in plain language."
    )

    st.divider()

    st.markdown("### Try these questions")

    example_questions = {
        "📋 SOP / Procedure": [
            "What are the escalation steps if FA-01 has been down for 20 minutes?",
            "Who needs to sign off after a trim line changeover first-off failure?",
            "What containment actions are required when we find 25 suspect units?",
            "What are the steps before handling a high-voltage battery pack on EV-BAT?",
        ],
        "📊 Live Line Data": [
            "What is the current OEE on FA-01?",
            "Show me the latest quality defect breakdown for TRIM-02.",
            "What downtime events has EV-BAT had in the last 24 hours?",
            "How is FA-02 performing right now — OEE and quality?",
        ],
        "🎫 Ticket Creation": [
            "Raise a high severity ticket for EV-BAT — HV connector not seating on 3 consecutive units.",
            "Log a medium severity ticket for TRIM-01: repeated clip engagement failures at door trim station.",
            "Open a low severity ticket for FA-02: minor surface scratches appearing on outgoing units.",
        ],
    }

    for category, questions in example_questions.items():
        st.markdown(f"**{category}**")
        for q in questions:
            if st.button(q, key=q, use_container_width=True):
                st.session_state.pending_input = q

    st.divider()

    st.markdown(
        "<small>**Data disclosure:** All MES metrics (OEE, quality, downtime) "
        "are procedurally generated by a mock API. No real manufacturing equipment "
        "is connected. SOP documents are illustrative examples.</small>",
        unsafe_allow_html=True,
    )

    if st.button("🗑 Clear conversation", use_container_width=True):
        st.session_state.messages = []
        st.rerun()

# ---------------------------------------------------------------------------
# Main area — header
# ---------------------------------------------------------------------------

st.title("🏭 Shopfloor Copilot")
st.markdown(
    "**Portfolio demo** · This application demonstrates a LangGraph-based AI agent "
    "that combines retrieval-augmented generation over manufacturing SOPs with live "
    "data from a simulated MES (Manufacturing Execution System) API. "
    "The agent can answer procedural questions, surface real-time line metrics, and "
    "raise formal incident tickets — all via a conversational interface. "
    "MES data shown is **simulated** and does not represent any real production plant."
)
st.divider()

# ---------------------------------------------------------------------------
# Session state — message history
# ---------------------------------------------------------------------------

if "messages" not in st.session_state:
    st.session_state.messages = []

# ---------------------------------------------------------------------------
# Render existing conversation
# ---------------------------------------------------------------------------

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# ---------------------------------------------------------------------------
# Handle sidebar example button clicks
# ---------------------------------------------------------------------------

prefill = st.session_state.pop("pending_input", None)

# ---------------------------------------------------------------------------
# Chat input
# ---------------------------------------------------------------------------

user_input = st.chat_input("Ask about a procedure, line performance, or raise a ticket…") or prefill

if user_input:
    # Append and display the user message
    st.session_state.messages.append({"role": "user", "content": user_input})
    with st.chat_message("user"):
        st.markdown(user_input)

    # Call the agent and stream the response into the chat bubble
    with st.chat_message("assistant"):
        with st.spinner("Thinking…"):
            try:
                response = run_agent(user_input)
            except Exception as exc:
                response = (
                    f"⚠️ The agent encountered an error: `{exc}`\n\n"
                    "Please check that the MES API is running on port 8000 "
                    "and that your `ANTHROPIC_API_KEY` is set correctly in `.env`."
                )
        st.markdown(response)

    # Persist the assistant response
    st.session_state.messages.append({"role": "assistant", "content": response})
